version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-otp
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - otp-network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-otp
    ports:
      - 1025:1025
      - 8025:8025
    expose:
      - 1025
      - 8025
    networks:
      - otp-network
networks:
  otp-network: