version: "3.9"

services:
  redis:
    image: redis
    container_name: redis-otp
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./_docker-data/redis:/data
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - otp-webapp-network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-otp
    ports:
      - 1025:1025
      - 8025:8025
    expose:
      - 1025
      - 8025
    networks:
      - otp-webapp-network
networks:
  otp-webapp-network: